# Generated by Django 5.0.3 on 2024-03-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='score',
        ),
        migrations.AddField(
            model_name='submission',
            name='score_disturbances',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_ideal',
            field=models.FloatField(default=1000),
        ),
        migrations.AddField(
            model_name='submission',
            name='score_noise',
            field=models.FloatField(default=1000),
        ),
    ]
